version: '3.8'
services:
  backend:
    image: backend-api:latest
    container_name: backend-server
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    networks:
      - net
  
  frontend:
    image: frontendapp:latest
    container_name:  frontend-container
    environment: 
      - PORT=8000
    ports:
      -  "8000:8000"
    networks:
      - net

networks:
  net:
    driver: bridge
